// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnGMwJYzsOp4_7WxC8CiN0Y4XBk-gNomc',
    appId: '1:787190721610:web:57921c0bf2523985274ab3',
    messagingSenderId: '787190721610',
    projectId: 'br-sma',
    authDomain: 'br-sma.firebaseapp.com',
    storageBucket: 'br-sma.appspot.com',
    measurementId: 'G-1MV3HFZN78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnGMwJYzsOp4_7WxC8CiN0Y4XBk-gNomc',
    appId: '1:787190721610:web:57921c0bf2523985274ab3',
    messagingSenderId: '787190721610',
    projectId: 'br-sma',
    authDomain: 'br-sma.firebaseapp.com',
    storageBucket: 'br-sma.appspot.com',
    measurementId: 'G-1MV3HFZN78',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVWU-koupGk6wsdV_VwA2Yh7zAwXeutM8',
    appId: '1:787190721610:ios:abbbbbb3004121da274ab3',
    messagingSenderId: '787190721610',
    projectId: 'br-sma',
    storageBucket: 'br-sma.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVWU-koupGk6wsdV_VwA2Yh7zAwXeutM8',
    appId: '1:787190721610:ios:abbbbbb3004121da274ab3',
    messagingSenderId: '787190721610',
    projectId: 'br-sma',
    storageBucket: 'br-sma.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLlBrCSo7UfiGcdaC9heRhQEM_jbRA8Zg',
    appId: '1:787190721610:web:8e5e8268a5c6f2d1274ab3',
    messagingSenderId: '787190721610',
    projectId: 'br-sma',
    authDomain: 'br-sma.firebaseapp.com',
    storageBucket: 'br-sma.appspot.com',
    measurementId: 'G-EQPN1MRWE4',
  );
}
